// ========================================
// Dados Mock para demonstração
// ========================================

import { Cliente, Tarefa, Anotacao, Anexo, CustoOperacional, Projeto, ProjetoPage } from '@/types';

export const mockClientes: Cliente[] = [
    {
        id: '1',
        nome: 'Sabor & Arte Restaurante',
        email: 'contato@saborarte.com.br',
        telefone: '(11) 98765-4321',
        servico: 'Gestão de Redes Sociais',
        valor_mensal: 2500,
        tipo_contrato: 'contrato_fixo',
        categoria: 'criacao_conteudo',
        data_inicio: '2025-03-01',
        status: 'ativo',
        observacoes: 'Cliente desde março. Foco em Instagram e TikTok. Postar 5x por semana.',
        created_at: '2025-03-01T10:00:00Z',
    },
    {
        id: '2',
        nome: 'TechFlow Solutions',
        email: 'marketing@techflow.io',
        telefone: '(21) 97654-3210',
        servico: 'Tráfego Pago',
        valor_mensal: 4000,
        tipo_contrato: 'contrato_fixo',
        categoria: 'trafego',
        data_inicio: '2025-01-15',
        status: 'ativo',
        observacoes: 'Google Ads + Meta Ads. Budget mensal de R$8.000. Relatório semanal.',
        created_at: '2025-01-15T14:30:00Z',
    },
    {
        id: '3',
        nome: 'Bella Moda Feminina',
        email: 'bella@bellamoda.com.br',
        telefone: '(31) 96543-2109',
        servico: 'Gestão de Redes Sociais + Tráfego Pago',
        valor_mensal: 5500,
        tipo_contrato: 'contrato_fixo',
        categoria: 'trafego',
        data_inicio: '2024-11-01',
        status: 'ativo',
        observacoes: 'E-commerce de moda. Instagram, Facebook e Pinterest. Budget ads: R$5.000.',
        created_at: '2024-11-01T09:00:00Z',
    },
    {
        id: '4',
        nome: 'Dr. Ricardo Mendes',
        email: 'ricardo@clinicamendes.com.br',
        telefone: '(11) 95432-1098',
        servico: 'Landing Page + Tráfego Pago',
        valor_mensal: 3000,
        tipo_contrato: 'freelance',
        categoria: 'freela',
        data_inicio: '2025-12-01',
        status: 'ativo',
        observacoes: 'Campanha para clínica odontológica. Prazo: 2 meses. Foco em leads.',
        created_at: '2025-12-01T11:00:00Z',
    },
    {
        id: '5',
        nome: 'GreenFit Academia',
        email: 'contato@greenfit.com.br',
        telefone: '(41) 94321-0987',
        servico: 'Gestão de Redes Sociais',
        valor_mensal: 1800,
        tipo_contrato: 'contrato_fixo',
        categoria: 'criacao_conteudo',
        data_inicio: '2025-06-01',
        status: 'pausado',
        observacoes: 'Cliente pausou em dezembro, pretende voltar em fevereiro.',
        created_at: '2025-06-01T08:00:00Z',
    },
    {
        id: '6',
        nome: 'Pizzaria do Zé',
        email: 'ze@pizzariadoze.com.br',
        telefone: '(11) 93210-9876',
        servico: 'Criação de Cardápio Digital',
        valor_mensal: 1500,
        tipo_contrato: 'freelance',
        categoria: 'freela',
        data_inicio: '2025-10-15',
        status: 'encerrado',
        observacoes: 'Projeto concluído. Cardápio digital + QR Code entregues.',
        created_at: '2025-10-15T16:00:00Z',
    },
    {
        id: '7',
        nome: 'Studio Yoga Zen',
        email: 'namaste@yogazen.com.br',
        telefone: '(51) 92109-8765',
        servico: 'Gestão de Redes Sociais + Email Marketing',
        valor_mensal: 3200,
        tipo_contrato: 'contrato_fixo',
        categoria: 'criacao_conteudo',
        data_inicio: '2025-08-01',
        status: 'ativo',
        observacoes: 'Instagram + newsletter semanal. Público-alvo: mulheres 25-45 anos.',
        created_at: '2025-08-01T10:30:00Z',
    },
    {
        id: '8',
        nome: 'AutoPeças Express',
        email: 'vendas@autopecas.com.br',
        telefone: '(19) 91098-7654',
        servico: 'Google Ads',
        valor_mensal: 2000,
        tipo_contrato: 'freelance',
        categoria: 'trafego',
        data_inicio: '2026-01-10',
        status: 'ativo',
        observacoes: 'Campanha de 3 meses para e-commerce. Foco em Google Shopping.',
        created_at: '2026-01-10T13:00:00Z',
    },
];

export const mockTarefas: Tarefa[] = [
    {
        id: 't1',
        cliente_id: '1',
        titulo: 'Criar calendário editorial fevereiro',
        descricao: 'Planejar 20 posts para Instagram e 8 para TikTok',
        status: 'em_andamento',
        prioridade: 'alta',
        prazo: '2026-02-15',
        created_at: '2026-02-01T10:00:00Z',
        completed_at: null,
    },
    {
        id: 't2',
        cliente_id: '1',
        titulo: 'Gravar reels de receitas',
        descricao: 'Agendar gravação no restaurante. Mínimo 4 reels.',
        status: 'a_fazer',
        prioridade: 'media',
        prazo: '2026-02-20',
        created_at: '2026-02-05T09:00:00Z',
        completed_at: null,
    },
    {
        id: 't3',
        cliente_id: '2',
        titulo: 'Otimizar campanhas Google Ads',
        descricao: 'Revisar palavras-chave negativas e ajustar lances',
        status: 'a_fazer',
        prioridade: 'alta',
        prazo: '2026-02-16',
        created_at: '2026-02-10T14:00:00Z',
        completed_at: null,
    },
    {
        id: 't4',
        cliente_id: '2',
        titulo: 'Relatório semanal de performance',
        descricao: 'Compilar dados de Google Ads e Meta Ads da semana',
        status: 'em_andamento',
        prioridade: 'media',
        prazo: '2026-02-14',
        created_at: '2026-02-10T08:00:00Z',
        completed_at: null,
    },
    {
        id: 't5',
        cliente_id: '3',
        titulo: 'Sessão de fotos coleção verão',
        descricao: 'Coordenar com fotógrafo. Local: estúdio centro.',
        status: 'concluida',
        prioridade: 'alta',
        prazo: '2026-02-10',
        created_at: '2026-01-25T11:00:00Z',
        completed_at: '2026-02-09T17:00:00Z',
    },
    {
        id: 't6',
        cliente_id: '3',
        titulo: 'Configurar catálogo Facebook Shop',
        descricao: 'Subir 50 produtos novos com fotos e preços',
        status: 'em_andamento',
        prioridade: 'media',
        prazo: '2026-02-18',
        created_at: '2026-02-05T10:00:00Z',
        completed_at: null,
    },
    {
        id: 't7',
        cliente_id: '4',
        titulo: 'Desenvolver landing page',
        descricao: 'Design + desenvolvimento da LP para captação de leads',
        status: 'em_andamento',
        prioridade: 'alta',
        prazo: '2026-02-20',
        created_at: '2026-01-20T09:00:00Z',
        completed_at: null,
    },
    {
        id: 't8',
        cliente_id: '4',
        titulo: 'Configurar pixel e conversões',
        descricao: 'Instalar pixel do Meta e configurar eventos de conversão',
        status: 'a_fazer',
        prioridade: 'alta',
        prazo: '2026-02-22',
        created_at: '2026-02-01T14:00:00Z',
        completed_at: null,
    },
    {
        id: 't9',
        cliente_id: '7',
        titulo: 'Newsletter semanal - Yoga em casa',
        descricao: 'Escrever e enviar newsletter com dicas de yoga para praticar em casa',
        status: 'a_fazer',
        prioridade: 'media',
        prazo: '2026-02-17',
        created_at: '2026-02-12T08:00:00Z',
        completed_at: null,
    },
    {
        id: 't10',
        cliente_id: '7',
        titulo: 'Stories depoimentos de alunos',
        descricao: 'Coletar e postar 5 depoimentos em stories com design padrão',
        status: 'concluida',
        prioridade: 'baixa',
        prazo: '2026-02-08',
        created_at: '2026-02-01T10:00:00Z',
        completed_at: '2026-02-07T15:00:00Z',
    },
    {
        id: 't11',
        cliente_id: '8',
        titulo: 'Estruturar campanhas Google Shopping',
        descricao: 'Criar campanhas de Shopping para as principais categorias',
        status: 'em_andamento',
        prioridade: 'alta',
        prazo: '2026-02-19',
        created_at: '2026-01-15T11:00:00Z',
        completed_at: null,
    },
    {
        id: 't12',
        cliente_id: '8',
        titulo: 'Feed de produtos - otimização',
        descricao: 'Revisar títulos e descrições do feed do Merchant Center',
        status: 'a_fazer',
        prioridade: 'media',
        prazo: '2026-02-25',
        created_at: '2026-02-10T09:00:00Z',
        completed_at: null,
    },
    {
        id: 't13',
        cliente_id: '1',
        titulo: 'Responder DMs e comentários',
        descricao: 'Engajamento diário nas redes sociais',
        status: 'concluida',
        prioridade: 'baixa',
        prazo: '2026-02-07',
        created_at: '2026-02-03T08:00:00Z',
        completed_at: '2026-02-07T18:00:00Z',
    },
    {
        id: 't14',
        cliente_id: '3',
        titulo: 'Campanha de Carnaval',
        descricao: 'Criar campanha promocional de Carnaval com 20% off',
        status: 'concluida',
        prioridade: 'alta',
        prazo: '2026-02-12',
        created_at: '2026-02-01T09:00:00Z',
        completed_at: '2026-02-11T16:00:00Z',
    },
    {
        id: 't15',
        cliente_id: '2',
        titulo: 'A/B test de criativos',
        descricao: 'Testar 3 variações de anúncios no Meta Ads',
        status: 'a_fazer',
        prioridade: 'media',
        prazo: '2026-02-21',
        created_at: '2026-02-12T14:00:00Z',
        completed_at: null,
    },
    {
        id: 't16',
        cliente_id: '7',
        titulo: 'Post colaborativo com influencer',
        descricao: 'Coordenar post colaborativo com @yogalife_br',
        status: 'a_fazer',
        prioridade: 'baixa',
        prazo: '2026-02-28',
        created_at: '2026-02-13T10:00:00Z',
        completed_at: null,
    },
];

export const mockAnotacoes: Anotacao[] = [
    {
        id: 'a1',
        cliente_id: '1',
        titulo: 'Briefing inicial',
        conteudo: 'Cliente quer foco em pratos do dia e bastidores da cozinha. Tom descontraído e apetitoso. Evitar posts muito formais.',
        created_at: '2025-03-02T10:00:00Z',
    },
    {
        id: 'a2',
        cliente_id: '1',
        titulo: 'Reunião mensal - Janeiro',
        conteudo: 'Feedback positivo. Engagement subiu 35%. Querem mais reels. Possibilidade de aumentar budget para ads em março.',
        created_at: '2026-01-30T14:00:00Z',
    },
    {
        id: 'a3',
        cliente_id: '2',
        titulo: 'Estratégia Q1 2026',
        conteudo: 'Foco em leads B2B. Testar LinkedIn Ads apart from Google/Meta. CPA target: R$45. Meeting semanal às terças 10h.',
        created_at: '2026-01-10T09:00:00Z',
    },
    {
        id: 'a4',
        cliente_id: '3',
        titulo: 'Paleta de cores aprovada',
        conteudo: 'Rosa (#FF6B9D), Branco, Preto, Dourado como accent. Font: Playfair Display para títulos, Montserrat para corpo.',
        created_at: '2024-11-05T11:00:00Z',
    },
    {
        id: 'a5',
        cliente_id: '3',
        titulo: 'Promoções recorrentes',
        conteudo: 'Toda primeira segunda do mês: 15% off novidades. Black Friday e Natal são as maiores campanhas do ano.',
        created_at: '2025-01-15T10:00:00Z',
    },
    {
        id: 'a6',
        cliente_id: '7',
        titulo: 'Personas definidas',
        conteudo: 'Maria (30, executiva, busca relaxamento), Ana (45, mãe, busca saúde), Lucia (25, estudante, busca fitness).',
        created_at: '2025-08-05T09:00:00Z',
    },
    {
        id: 'a7',
        cliente_id: '4',
        titulo: 'Requisitos da landing page',
        conteudo: 'Seções: Hero com CTA, Antes/Depois, Depoimentos, Formulário. Integrar com RD Station. Tempo de carregamento < 3s.',
        created_at: '2025-12-05T10:00:00Z',
    },
];

export const mockAnexos: Anexo[] = [
    {
        id: 'ax1',
        cliente_id: '1',
        nome_arquivo: 'logo_sabor_arte.png',
        url: '#',
        tipo: 'image/png',
        tamanho: 245000,
        created_at: '2025-03-01T10:00:00Z',
    },
    {
        id: 'ax2',
        cliente_id: '3',
        nome_arquivo: 'manual_marca_bella.pdf',
        url: '#',
        tipo: 'application/pdf',
        tamanho: 3200000,
        created_at: '2024-11-02T09:00:00Z',
    },
    {
        id: 'ax3',
        cliente_id: '2',
        nome_arquivo: 'relatorio_janeiro_2026.xlsx',
        url: '#',
        tipo: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        tamanho: 156000,
        created_at: '2026-02-01T15:00:00Z',
    },
    {
        id: 'ax4',
        cliente_id: '4',
        nome_arquivo: 'wireframe_landing_page.pdf',
        url: '#',
        tipo: 'application/pdf',
        tamanho: 890000,
        created_at: '2025-12-10T11:00:00Z',
    },
];

export const mockCustos: CustoOperacional[] = [
    {
        id: 'c1',
        descricao: 'Canva Pro',
        valor: 55,
        categoria: 'Software',
        data: '2026-02-01',
        recorrente: true,
        created_at: '2025-01-01T00:00:00Z',
    },
    {
        id: 'c2',
        descricao: 'Adobe Creative Cloud',
        valor: 290,
        categoria: 'Software',
        data: '2026-02-01',
        recorrente: true,
        created_at: '2025-01-01T00:00:00Z',
    },
    {
        id: 'c3',
        descricao: 'mLabs (agendamento)',
        valor: 60,
        categoria: 'Software',
        data: '2026-02-01',
        recorrente: true,
        created_at: '2025-06-01T00:00:00Z',
    },
    {
        id: 'c4',
        descricao: 'Internet Fibra 500MB',
        valor: 150,
        categoria: 'Infraestrutura',
        data: '2026-02-05',
        recorrente: true,
        created_at: '2024-01-01T00:00:00Z',
    },
    {
        id: 'c5',
        descricao: 'Curso Tráfego Avançado',
        valor: 497,
        categoria: 'Educação',
        data: '2026-01-15',
        recorrente: false,
        created_at: '2026-01-15T00:00:00Z',
    },
];

// Dados de receita mensal para gráficos (últimos 6 meses)
export const mockRevenueData = [
    { month: 'Set/25', receita: 14200, custos: 555, lucro: 13645 },
    { month: 'Out/25', receita: 15700, custos: 555, lucro: 15145 },
    { month: 'Nov/25', receita: 16200, custos: 1052, lucro: 15148 },
    { month: 'Dez/25', receita: 13800, custos: 555, lucro: 13245 },
    { month: 'Jan/26', receita: 17200, custos: 1052, lucro: 16148 },
    { month: 'Fev/26', receita: 18200, custos: 555, lucro: 17645 },
];

// Dados do heatmap de produtividade (últimos 90 dias)
export function generateHeatmapData(): Record<string, number> {
    const data: Record<string, number> = {};
    const today = new Date();
    for (let i = 0; i < 90; i++) {
        const date = new Date(today);
        date.setDate(date.getDate() - i);
        const key = date.toISOString().split('T')[0];
        // Peso aleatório com mais chances de dias produtivos em dias de semana
        const dayOfWeek = date.getDay();
        if (dayOfWeek === 0) {
            data[key] = Math.random() > 0.7 ? Math.floor(Math.random() * 2) : 0;
        } else if (dayOfWeek === 6) {
            data[key] = Math.random() > 0.5 ? Math.floor(Math.random() * 3) : 0;
        } else {
            data[key] = Math.floor(Math.random() * 5) + 1;
        }
    }
    return data;
}

// ========================================
// Projetos - Workspace Notion-like
// ========================================

export const mockProjetos: Projeto[] = [
    {
        id: 'p1',
        nome: 'Estratégias Meta Ads 2026',
        descricao: 'Estudo completo sobre otimização de campanhas no Meta Ads',
        emoji: '🚀',
        cor: '#3B82F6',
        created_at: '2026-01-10T10:00:00Z',
    },
    {
        id: 'p2',
        nome: 'Curso de Copywriting',
        descricao: 'Anotações e exercícios do curso de copy para vendas',
        emoji: '✍️',
        cor: '#8B5CF6',
        created_at: '2026-01-20T14:00:00Z',
    },
    {
        id: 'p3',
        nome: 'Estudo de Funis de Venda',
        descricao: 'Modelagem de funis para diferentes nichos de mercado',
        emoji: '🎯',
        cor: '#10B981',
        created_at: '2026-02-01T09:00:00Z',
    },
];

export const mockProjetoPages: ProjetoPage[] = [
    {
        id: 'pp1',
        projeto_id: 'p1',
        titulo: 'Estrutura de Campanha',
        emoji: '📊',
        blocks: [
            { id: 'b1', type: 'heading1', content: 'Estrutura de Campanha Meta Ads' },
            { id: 'b2', type: 'text', content: 'Uma campanha bem estruturada é a base para resultados consistentes. Aqui estão os pilares fundamentais que uso em todos os meus clientes.' },
            { id: 'b3', type: 'heading2', content: 'Hierarquia de Campanha' },
            { id: 'b4', type: 'checklist', content: 'Definir objetivo da campanha (Conversão, Tráfego, Engajamento)', checked: true },
            { id: 'b5', type: 'checklist', content: 'Criar conjuntos de anúncios por público', checked: true },
            { id: 'b6', type: 'checklist', content: 'Preparar 3-5 criativos por conjunto', checked: false },
            { id: 'b7', type: 'checklist', content: 'Configurar pixel e eventos de conversão', checked: false },
            { id: 'b8', type: 'divider', content: '' },
            { id: 'b9', type: 'heading2', content: 'Orçamento Recomendado' },
            { id: 'b10', type: 'text', content: 'Para campanhas de conversão, recomendo no mínimo R$30/dia por conjunto de anúncios. Isso permite que o algoritmo do Meta otimize com dados suficientes.' },
            { id: 'b11', type: 'quote', content: 'Regra de ouro: nunca otimize uma campanha antes de 50 conversões. O algoritmo precisa de dados.' },
        ],
        created_at: '2026-01-10T10:00:00Z',
        updated_at: '2026-02-10T15:30:00Z',
    },
    {
        id: 'pp2',
        projeto_id: 'p1',
        titulo: 'Públicos e Segmentação',
        emoji: '🎯',
        blocks: [
            { id: 'b12', type: 'heading1', content: 'Estratégias de Público' },
            { id: 'b13', type: 'text', content: 'Segmentação é onde a mágica acontece. Dividir públicos corretamente pode reduzir CPA em até 60%.' },
            { id: 'b14', type: 'heading2', content: 'Tipos de Público' },
            { id: 'b15', type: 'text', content: '1. **Frio** — Interesses e lookalikes amplos\n2. **Morno** — Visitou site, engajou nos últimos 30 dias\n3. **Quente** — Adicionou ao carrinho, iniciou checkout' },
            { id: 'b16', type: 'code', content: '// Exemplo de evento personalizado\nfbq("track", "Lead", {\n  content_name: "Formulario Contato",\n  value: 100.00,\n  currency: "BRL"\n});', language: 'javascript' },
        ],
        created_at: '2026-01-12T09:00:00Z',
        updated_at: '2026-02-08T11:00:00Z',
    },
    {
        id: 'pp3',
        projeto_id: 'p2',
        titulo: 'Gatilhos Mentais',
        emoji: '🧠',
        blocks: [
            { id: 'b17', type: 'heading1', content: 'Gatilhos Mentais em Copy' },
            { id: 'b18', type: 'text', content: 'Os gatilhos mentais são atalhos psicológicos que influenciam a tomada de decisão. Dominar esses gatilhos é essencial para qualquer copywriter.' },
            { id: 'b19', type: 'heading2', content: 'Principais Gatilhos' },
            { id: 'b20', type: 'checklist', content: 'Escassez — "Restam apenas 3 vagas"', checked: true },
            { id: 'b21', type: 'checklist', content: 'Urgência — "Oferta válida até meia-noite"', checked: true },
            { id: 'b22', type: 'checklist', content: 'Prova Social — "Mais de 500 alunos satisfeitos"', checked: true },
            { id: 'b23', type: 'checklist', content: 'Autoridade — "Reconhecido pelo Google"', checked: false },
            { id: 'b24', type: 'checklist', content: 'Reciprocidade — "Conteúdo gratuito de valor"', checked: false },
            { id: 'b25', type: 'divider', content: '' },
            { id: 'b26', type: 'quote', content: 'A melhor copy não é a que vende mais, é a que faz o cliente sentir que a decisão foi dele. — Joseph Sugarman' },
        ],
        created_at: '2026-01-20T14:00:00Z',
        updated_at: '2026-02-05T10:00:00Z',
    },
    {
        id: 'pp4',
        projeto_id: 'p2',
        titulo: 'Frameworks de Copy',
        emoji: '📋',
        blocks: [
            { id: 'b27', type: 'heading1', content: 'Frameworks de Copywriting' },
            { id: 'b28', type: 'heading2', content: 'AIDA' },
            { id: 'b29', type: 'text', content: '**A**tenção → **I**nteresse → **D**esejo → **A**ção\n\nO clássico dos clássicos. Funciona especialmente bem para páginas de venda e emails.' },
            { id: 'b30', type: 'heading2', content: 'PAS' },
            { id: 'b31', type: 'text', content: '**P**roblema → **A**gitação → **S**olução\n\nIdeal para emails de venda e textos de anúncio. Começa com a dor do cliente.' },
            { id: 'b32', type: 'heading2', content: 'BAB' },
            { id: 'b33', type: 'text', content: '**B**efore → **A**fter → **B**ridge\n\nMostra a transformação. Ótimo para depoimentos e estudos de caso.' },
        ],
        created_at: '2026-01-22T11:00:00Z',
        updated_at: '2026-02-03T16:00:00Z',
    },
    {
        id: 'pp5',
        projeto_id: 'p3',
        titulo: 'Funil de Vendas B2B',
        emoji: '🏢',
        blocks: [
            { id: 'b34', type: 'heading1', content: 'Funil de Vendas B2B — SaaS' },
            { id: 'b35', type: 'text', content: 'Modelo de funil otimizado para empresas de software que vendem para outras empresas.' },
            { id: 'b36', type: 'heading2', content: 'Etapas do Funil' },
            { id: 'b37', type: 'text', content: '1. **Topo** — Conteúdo educativo (blog, webinar)\n2. **Meio** — E-book, trial grátis, demo\n3. **Fundo** — Proposta comercial, reunião de vendas' },
            { id: 'b38', type: 'heading2', content: 'Métricas-Chave' },
            { id: 'b39', type: 'checklist', content: 'Custo por Lead (CPL) < R$25', checked: false },
            { id: 'b40', type: 'checklist', content: 'Taxa de conversão Lead → MQL > 20%', checked: false },
            { id: 'b41', type: 'checklist', content: 'Taxa de conversão MQL → SQL > 30%', checked: false },
            { id: 'b42', type: 'checklist', content: 'Ciclo de venda < 45 dias', checked: false },
        ],
        created_at: '2026-02-01T09:00:00Z',
        updated_at: '2026-02-12T14:00:00Z',
    },
];
